- name: Variables from files
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Im learning {{Course}}, Trainer is {{Trainer}} and Duration is {{Duration}}"